CURRENT_MAKEFILE := $(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))
MAKEFILE_DIRECTORY := $(dir $(CURRENT_MAKEFILE))

TOOLPREFIX=i686-pc-elf-
TOOLPATH=$(MAKEFILE_DIRECTORY)toolchain/gcc/bin/

CC = $(MAKEFILE_DIRECTORY)toolchain/clang/bin/clang
AS = $(TOOLPATH)$(TOOLPREFIX)as
LD = $(TOOLPATH)$(TOOLPREFIX)ld

AR = $(TOOLPATH)$(TOOLPREFIX)ar
RANLIB = $(TOOLPATH)$(TOOLPREFIX)ranlib

OBJCOPY = $(TOOLPATH)$(TOOLPREFIX)objcopy
OBJDUMP = $(TOOLPATH)$(TOOLPREFIX)objdump

CFLAGS = -fno-builtin -nostdinc -fno-stack-protector -Wall

QEMU = qemu-system-i386
