
TOOLPREFIX=i686-pc-elf-

CC = $(TOOLPREFIX)gcc
AS = $(TOOLPREFIX)as
LD = $(TOOLPREFIX)ld

AR = $(TOOLPREFIX)ar

OBJCOPY = $(TOOLPREFIX)objcopy
OBJDUMP = $(TOOLPREFIX)objdump

CFLAGS = -fno-builtin -nostdinc -fno-stack-protector -Wall

